---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
      - id: trailing-whitespace   # Trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending     # Replaces or checks mixed line ending.
        args: [--fix=lf]
      - id: end-of-file-fixer     # Makes sure files end in a newline and only a newline.
        exclude: user_data/.*
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: check-ast             # Simply check whether files parse as valid python.
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: |
          (?x)^(
            .gitlab/ci/.*\.(json|yml|yaml)$|
            .gitlab-ci.yml
          )$
      - id: end-of-file-fixer
  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
        stages: [commit]

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.24.1
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
